---

- name: 'copy limits file'
  copy:
    src: es_limits.conf
    dest: /etc/security/limits.d/es_limits.conf
    owner: root
    group: root
    mode: 0644
  notify: restart sonar
  tags:
    - sonar
    - limits

- name: 'create sonar database'
  postgresql_db:
    name: sonar
    template: 'template0'
    encoding: 'UTF-8'
  tags:
    - sonar
    - sonarconfig
    - database
    - postgresql

- name: 'create sonar user'
  postgresql_user:
    db: sonar
    name: '{{ sonar_username }}'
    password: '{{ sonar_password }}'
  tags:
    - sonar
    - sonarconfig
    - database
    - postgresql

# In order to add section to the sonar.properties file (thanks to assemble directive)
- name: 'create directory'
  file:
    dest: "{{ sonar_home }}/{{ sonar_name }}/conf/properties"
    state: directory

- name: 'configure sonar.properties'
  template:
    src: sonar.properties
    dest: "{{ sonar_home }}/{{ sonar_name }}/conf/sonar.properties"
  notify: restart sonar
  tags:
    - sonar
    - sonarconfig
