---

- name: 'make sure unzip is installed'
  become: yes
  yum:
    state: present
    name:
      - 'unzip'

- name: 'verify presence of Sonar'
  stat:
    path: "{{ sonar_home }}/bin/sonar"
  register: sonar_installed
  tags:
    - sonar

- name: 'create sonar group'
  group:
    name: sonar
  tags:
    - sonar

- name: 'create sonar user'
  user:
    name: sonar
    group: sonar
    home: "{{ sonar_home }}"
  tags:
    - sonar

- name: 'download Sonar'
  get_url:
    url: "{{ sonar_url }}"
    dest: /tmp
    validate_certs: false
  retries: 3
  when: not sonar_installed.stat.exists
  tags:
    - sonar

- name: 'create directory for Sonar installations'
  file:
    dest: "{{ sonar_home }}"
    state: directory
    owner: sonar
    group: sonar
    mode: 0755
  tags:
    - sonar

- name: 'unzip Sonar'
  unarchive:
    src: "/tmp/{{ sonar_file }}"
    dest: "{{ sonar_home }}"
    keep_newer: True
    remote_src: True

- name: 'fix directory for Sonar'
  file:
    dest: "{{ sonar_home }}"
    recurse: true
    owner: sonar
    group: sonar
  tags:
    - sonar

- name: 'install Sonar as a service'
  template:
    src: sonar.service
    dest: /etc/systemd/system
  tags:
    - sonar
    - sonarservice
